name: Actions

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  Build-Module-Pr7:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: chmod +x ./gradlew
        run: chmod +x ./gradlew
      - name: Build Module Pr7
        run: ./gradlew :pr7:assembleDebug 
        
      - name: Archive APK files
        run: |
          mkdir -p apk
          cp pr7/build/outputs/apk/debug/pr7-debug.apk apk/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: apk/

  Build-Module-Pr8:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: chmod +x ./gradlew
        run: chmod +x ./gradlew
      - name: Build Module Pr8
        run: ./gradlew :pr8:assembleDebug

      - name: Archive APK files
        run: |
          mkdir -p apk
          cp pr8/build/outputs/apk/debug/pr8-debug.apk apk/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: apk/

  Build-Module-Pr9:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: chmod +x ./gradlew
        run: chmod +x ./gradlew
      - name: Build Module Pr9
        run: ./gradlew :pr9:assembleDebug

      - name: Archive APK files
        run: |
          mkdir -p apk
          cp pr9/build/outputs/apk/debug/pr9-debug.apk apk/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: apk/